fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  desc "Release new version"
  lane :bump_version do |options|

    version = options[:version]

    version_bump_podspec(version_number: version)
    git_commit(
      message: "Bump up version to #{version}",
      path: ["./*"]
    )
    add_git_tag(
      tag: version
    )
    push_to_git_remote
    pod_push
  end

end

