fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  desc "Release new version"
  lane :bump_version do |options|

    version = options[:version]
    if version.to_s.empty?
      version_bump_podspec(bump_type: "patch")
      version = lane_context[SharedValues::PODSPEC_VERSION_NUMBER]
    else
      version_bump_podspec(version_number: version)  
    end
    
    git_commit(
      message: "Bump up version to #{version}",
      path: ["./*"]
    )
    add_git_tag(
      tag: version
    )
    push_to_git_remote
    pod_push(swift_version: "4.2")
  end

end

